#Afin de générer le mot de passe en base64
#echo -n 'Test124=' | base64
#VGVzdDEyND0=

#création secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: YWRtaW4=

