#ajout d'un pod avec à partir de l'image Heroes-back-end avec replicas de 5
apiVersion: v1
kind: ReplicationController
metadata:
  name: heroes-back-end-rc
spec:
  replicas: 5
    selector:
      app: heroes-back-end
    template:
      metadata:
        labels:
          app: heroes-back-end
      spec:
       containers:
         - name: heroes-back-end-pod
           image: registry.gitlab.com/cogcoursedevops/kubernetes_heroes_app:latest
           ports:
             - containerPort: 5000
