apiVersion: v1
data:
  allow-snippet-annotations: "true" #permet à l'utilisateur d'ajouter des directives a exécuter !!! uniquement si vous pouvez faire confiance aux utilisateurs
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx